{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import tkinter as tk\n",
    "from tkinter import *\n",
    "from PIL import Image , ImageTk\n",
    "import cv2\n",
    "import threading"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "from keras.models import load_model\n",
    "model = load_model('model.h5')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "emotion = {0:\"Angry\",1:\"Disgusted\",2:\"Fearful\",3:\"Happy\",4:\"Neutral\",5:\"Sad\",6:\"Surprised\"}\n",
    "import os\n",
    "path=os.path.dirname(os.path.abspath(\"__file__\"))\n",
    "emoji={\n",
    "0:path+\"/DATA/EMOJIS/ANGRY.png\",\n",
    "1:path+\"/DATA/EMOJIS/DISGUSTED.png\",\n",
    "2:path+\"/DATA/EMOJIS/FEARFUL.png\",\n",
    "3:path+\"/DATA/EMOJIS/HAPPY.png\",\n",
    "4:path+\"/DATA/EMOJIS/NEUTRAL.png\",\n",
    "5:path+\"/DATA/EMOJIS/SAD.png\",\n",
    "6:path+\"/DATA/EMOJIS/SURPRISED.png\"\n",
    "}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "global last_frame1\n",
    "last_frame1=np.zeros((480,640,3),dtype=np.uint8)\n",
    "global cap1\n",
    "show_text=[0]\n",
    "global frame_number\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "def show_subject():\n",
    "    cap1=cv2.VideoCapture(0)\n",
    "    if not cap1.isOpened():\n",
    "        print(\"UNABLE TO ACCESS CAMERA\")\n",
    "    global frame_number\n",
    "    length=int(cap1.get(cv2.CAP_PROP_FRAME_COUNT))\n",
    "    frame_number+=1\n",
    "    if frame_number>=length:\n",
    "        exit()\n",
    "    cap1.set(1,frame_number)\n",
    "    flag1,frame1=cap1.read()\n",
    "    frame1=cv2.resize(frame1,(300,400))\n",
    "    bounding_box=cv2.CascadeClassifier(\"C:/Users/hp/anaconda3/Lib/site-packages/cv2/data/haarcascade_frontalface_default.xml\")\n",
    "    gray_frame=cv2.cvtColor(frame1,cv2.COLOR_BGR2GRAY)\n",
    "    num_faces=bounding_box.detectMultiScale(gray_frame,scaleFactor=1.3,minNeighbors=5)\n",
    "    for(x,y,w,h)in num_faces:\n",
    "        cv2.rectangle(frame1,(x,y-50),(x+w,y+h+10),(255,0,0),2)\n",
    "        roi_gray_frame=gray_frame[y:y + h,x:x+w]\n",
    "        cropped_img=np.expand_dims(np.expand_dims(cv2.resize(roi_gray_frame,(48,48)),-1),0)\n",
    "        prediction=model.predict(cropped_img)\n",
    "        maxindex=int(np.argmax(prediction))\n",
    "        cv2.putText(frame1,emotion[maxindex],(x+20,y-60),cv2.FONT_HERSHEY_SIMPLEX,1,(255,255,255),2,cv2.LINE_AA)\n",
    "        show_text[0]=maxindex\n",
    "    if flag1 is None:\n",
    "        print(\"ERROR\")\n",
    "    elif flag1:\n",
    "        global last_frame1\n",
    "        last_frame1=frame1.copy()\n",
    "        pic=cv2.cvtColor(last_frame1,cv2.COLOR_BGR2RGB)\n",
    "        img=Image.fromarray(pic)\n",
    "        imgtk=ImageTk.PhotoImage(image=img)\n",
    "        lmain.imgtk=imgtk\n",
    "        lmain.configure(image=imgtk)\n",
    "        root.update()\n",
    "        lmain.after(10,show_subject)\n",
    "    if cv2.waitkey(1) & 0xFF == ord(\"q\"):\n",
    "        exit()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [],
   "source": [
    "def show_avatar():\n",
    "    frame2=cv2.imread(emoji[show_text[0]])\n",
    "    pic2=cv2.cvtColor(frame2,cv2.COLOR_BGR2RGB)\n",
    "    img2=Image.fromarray(frame2)\n",
    "    imgtk2=ImageTk.PhotoImage(image=img2)\n",
    "    lmain2.imgtk=imgtk2\n",
    "    lmain3.configure(text=emotion[show_text[0]],font=('arial',45,'bold'))\n",
    "    lmain2.configure(image=imgtk2)\n",
    "    root.update()\n",
    "    lmain2.after(10,show_avatar)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Thread-4:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\hp\\anaconda3\\lib\\threading.py\", line 932, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\hp\\anaconda3\\lib\\threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-5-971e101f8111>\", line 36, in show_subject\n",
      "AttributeError: module 'cv2' has no attribute 'waitkey'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\hp\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"c:\\Users\\hp\\anaconda3\\lib\\tkinter\\__init__.py\", line 814, in callit\n",
      "    func(*args)\n",
      "  File \"<ipython-input-5-971e101f8111>\", line 36, in show_subject\n",
      "    if cv2.waitkey(1) & 0xFF == ord(\"q\"):\n",
      "AttributeError: module 'cv2' has no attribute 'waitkey'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\hp\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"c:\\Users\\hp\\anaconda3\\lib\\tkinter\\__init__.py\", line 814, in callit\n",
      "    func(*args)\n",
      "  File \"<ipython-input-5-971e101f8111>\", line 36, in show_subject\n",
      "    if cv2.waitkey(1) & 0xFF == ord(\"q\"):\n",
      "AttributeError: module 'cv2' has no attribute 'waitkey'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\hp\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"c:\\Users\\hp\\anaconda3\\lib\\tkinter\\__init__.py\", line 814, in callit\n",
      "    func(*args)\n",
      "  File \"<ipython-input-5-971e101f8111>\", line 36, in show_subject\n",
      "    if cv2.waitkey(1) & 0xFF == ord(\"q\"):\n",
      "AttributeError: module 'cv2' has no attribute 'waitkey'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\hp\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"c:\\Users\\hp\\anaconda3\\lib\\tkinter\\__init__.py\", line 814, in callit\n",
      "    func(*args)\n",
      "  File \"<ipython-input-5-971e101f8111>\", line 36, in show_subject\n",
      "    if cv2.waitkey(1) & 0xFF == ord(\"q\"):\n",
      "AttributeError: module 'cv2' has no attribute 'waitkey'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\hp\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"c:\\Users\\hp\\anaconda3\\lib\\tkinter\\__init__.py\", line 814, in callit\n",
      "    func(*args)\n",
      "  File \"<ipython-input-5-971e101f8111>\", line 36, in show_subject\n",
      "    if cv2.waitkey(1) & 0xFF == ord(\"q\"):\n",
      "AttributeError: module 'cv2' has no attribute 'waitkey'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\hp\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"c:\\Users\\hp\\anaconda3\\lib\\tkinter\\__init__.py\", line 814, in callit\n",
      "    func(*args)\n",
      "  File \"<ipython-input-5-971e101f8111>\", line 36, in show_subject\n",
      "    if cv2.waitkey(1) & 0xFF == ord(\"q\"):\n",
      "AttributeError: module 'cv2' has no attribute 'waitkey'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\hp\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"c:\\Users\\hp\\anaconda3\\lib\\tkinter\\__init__.py\", line 814, in callit\n",
      "    func(*args)\n",
      "  File \"<ipython-input-5-971e101f8111>\", line 36, in show_subject\n",
      "    if cv2.waitkey(1) & 0xFF == ord(\"q\"):\n",
      "AttributeError: module 'cv2' has no attribute 'waitkey'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\hp\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"c:\\Users\\hp\\anaconda3\\lib\\tkinter\\__init__.py\", line 814, in callit\n",
      "    func(*args)\n",
      "  File \"<ipython-input-5-971e101f8111>\", line 36, in show_subject\n",
      "    if cv2.waitkey(1) & 0xFF == ord(\"q\"):\n",
      "AttributeError: module 'cv2' has no attribute 'waitkey'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\hp\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"c:\\Users\\hp\\anaconda3\\lib\\tkinter\\__init__.py\", line 814, in callit\n",
      "    func(*args)\n",
      "  File \"<ipython-input-5-971e101f8111>\", line 36, in show_subject\n",
      "    if cv2.waitkey(1) & 0xFF == ord(\"q\"):\n",
      "AttributeError: module 'cv2' has no attribute 'waitkey'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\hp\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"c:\\Users\\hp\\anaconda3\\lib\\tkinter\\__init__.py\", line 814, in callit\n",
      "    func(*args)\n",
      "  File \"<ipython-input-5-971e101f8111>\", line 36, in show_subject\n",
      "    if cv2.waitkey(1) & 0xFF == ord(\"q\"):\n",
      "AttributeError: module 'cv2' has no attribute 'waitkey'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\hp\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"c:\\Users\\hp\\anaconda3\\lib\\tkinter\\__init__.py\", line 814, in callit\n",
      "    func(*args)\n",
      "  File \"<ipython-input-5-971e101f8111>\", line 36, in show_subject\n",
      "    if cv2.waitkey(1) & 0xFF == ord(\"q\"):\n",
      "AttributeError: module 'cv2' has no attribute 'waitkey'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\hp\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"c:\\Users\\hp\\anaconda3\\lib\\tkinter\\__init__.py\", line 814, in callit\n",
      "    func(*args)\n",
      "  File \"<ipython-input-5-971e101f8111>\", line 36, in show_subject\n",
      "    if cv2.waitkey(1) & 0xFF == ord(\"q\"):\n",
      "AttributeError: module 'cv2' has no attribute 'waitkey'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\hp\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"c:\\Users\\hp\\anaconda3\\lib\\tkinter\\__init__.py\", line 814, in callit\n",
      "    func(*args)\n",
      "  File \"<ipython-input-5-971e101f8111>\", line 36, in show_subject\n",
      "    if cv2.waitkey(1) & 0xFF == ord(\"q\"):\n",
      "AttributeError: module 'cv2' has no attribute 'waitkey'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\hp\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"c:\\Users\\hp\\anaconda3\\lib\\tkinter\\__init__.py\", line 814, in callit\n",
      "    func(*args)\n",
      "  File \"<ipython-input-5-971e101f8111>\", line 36, in show_subject\n",
      "    if cv2.waitkey(1) & 0xFF == ord(\"q\"):\n",
      "AttributeError: module 'cv2' has no attribute 'waitkey'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\hp\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"c:\\Users\\hp\\anaconda3\\lib\\tkinter\\__init__.py\", line 814, in callit\n",
      "    func(*args)\n",
      "  File \"<ipython-input-5-971e101f8111>\", line 36, in show_subject\n",
      "    if cv2.waitkey(1) & 0xFF == ord(\"q\"):\n",
      "AttributeError: module 'cv2' has no attribute 'waitkey'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\hp\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"c:\\Users\\hp\\anaconda3\\lib\\tkinter\\__init__.py\", line 814, in callit\n",
      "    func(*args)\n",
      "  File \"<ipython-input-5-971e101f8111>\", line 36, in show_subject\n",
      "    if cv2.waitkey(1) & 0xFF == ord(\"q\"):\n",
      "AttributeError: module 'cv2' has no attribute 'waitkey'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\hp\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"c:\\Users\\hp\\anaconda3\\lib\\tkinter\\__init__.py\", line 814, in callit\n",
      "    func(*args)\n",
      "  File \"<ipython-input-5-971e101f8111>\", line 36, in show_subject\n",
      "    if cv2.waitkey(1) & 0xFF == ord(\"q\"):\n",
      "AttributeError: module 'cv2' has no attribute 'waitkey'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\hp\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"c:\\Users\\hp\\anaconda3\\lib\\tkinter\\__init__.py\", line 814, in callit\n",
      "    func(*args)\n",
      "  File \"<ipython-input-5-971e101f8111>\", line 36, in show_subject\n",
      "    if cv2.waitkey(1) & 0xFF == ord(\"q\"):\n",
      "AttributeError: module 'cv2' has no attribute 'waitkey'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\hp\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"c:\\Users\\hp\\anaconda3\\lib\\tkinter\\__init__.py\", line 814, in callit\n",
      "    func(*args)\n",
      "  File \"<ipython-input-5-971e101f8111>\", line 36, in show_subject\n",
      "    if cv2.waitkey(1) & 0xFF == ord(\"q\"):\n",
      "AttributeError: module 'cv2' has no attribute 'waitkey'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\hp\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"c:\\Users\\hp\\anaconda3\\lib\\tkinter\\__init__.py\", line 814, in callit\n",
      "    func(*args)\n",
      "  File \"<ipython-input-5-971e101f8111>\", line 36, in show_subject\n",
      "    if cv2.waitkey(1) & 0xFF == ord(\"q\"):\n",
      "AttributeError: module 'cv2' has no attribute 'waitkey'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\hp\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"c:\\Users\\hp\\anaconda3\\lib\\tkinter\\__init__.py\", line 814, in callit\n",
      "    func(*args)\n",
      "  File \"<ipython-input-5-971e101f8111>\", line 36, in show_subject\n",
      "    if cv2.waitkey(1) & 0xFF == ord(\"q\"):\n",
      "AttributeError: module 'cv2' has no attribute 'waitkey'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\hp\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"c:\\Users\\hp\\anaconda3\\lib\\tkinter\\__init__.py\", line 814, in callit\n",
      "    func(*args)\n",
      "  File \"<ipython-input-5-971e101f8111>\", line 36, in show_subject\n",
      "    if cv2.waitkey(1) & 0xFF == ord(\"q\"):\n",
      "AttributeError: module 'cv2' has no attribute 'waitkey'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\hp\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"c:\\Users\\hp\\anaconda3\\lib\\tkinter\\__init__.py\", line 814, in callit\n",
      "    func(*args)\n",
      "  File \"<ipython-input-5-971e101f8111>\", line 36, in show_subject\n",
      "    if cv2.waitkey(1) & 0xFF == ord(\"q\"):\n",
      "AttributeError: module 'cv2' has no attribute 'waitkey'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\hp\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"c:\\Users\\hp\\anaconda3\\lib\\tkinter\\__init__.py\", line 814, in callit\n",
      "    func(*args)\n",
      "  File \"<ipython-input-5-971e101f8111>\", line 36, in show_subject\n",
      "    if cv2.waitkey(1) & 0xFF == ord(\"q\"):\n",
      "AttributeError: module 'cv2' has no attribute 'waitkey'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\hp\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"c:\\Users\\hp\\anaconda3\\lib\\tkinter\\__init__.py\", line 814, in callit\n",
      "    func(*args)\n",
      "  File \"<ipython-input-5-971e101f8111>\", line 36, in show_subject\n",
      "    if cv2.waitkey(1) & 0xFF == ord(\"q\"):\n",
      "AttributeError: module 'cv2' has no attribute 'waitkey'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\hp\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"c:\\Users\\hp\\anaconda3\\lib\\tkinter\\__init__.py\", line 814, in callit\n",
      "    func(*args)\n",
      "  File \"<ipython-input-5-971e101f8111>\", line 36, in show_subject\n",
      "    if cv2.waitkey(1) & 0xFF == ord(\"q\"):\n",
      "AttributeError: module 'cv2' has no attribute 'waitkey'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\hp\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"c:\\Users\\hp\\anaconda3\\lib\\tkinter\\__init__.py\", line 814, in callit\n",
      "    func(*args)\n",
      "  File \"<ipython-input-5-971e101f8111>\", line 36, in show_subject\n",
      "    if cv2.waitkey(1) & 0xFF == ord(\"q\"):\n",
      "AttributeError: module 'cv2' has no attribute 'waitkey'\n"
     ]
    },
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31mThe Kernel crashed while executing code in the the current cell or a previous cell. Please review the code in the cell(s) to identify a possible cause of the failure. Click <a href='https://aka.ms/vscodeJupyterKernelCrash'>here</a> for more info. View Jupyter <a href='command:jupyter.viewOutput'>log</a> for further details."
     ]
    }
   ],
   "source": [
    "if __name__ == '__main__':\n",
    "    frame_number=0\n",
    "    root=tk.Tk()\n",
    "    lmain=tk.Label(master=root,padx=50,bd=10)\n",
    "    lmain2=tk.Label(master=root,bd=10)\n",
    "    lmain3=tk.Label(master=root,bd=10,fg='#CDCDCD',bg='black')\n",
    "    lmain.pack(side=LEFT)\n",
    "    lmain.place(x=50,y=250)\n",
    "    lmain3.pack()\n",
    "    lmain3.place(x=960,y=250)\n",
    "    lmain2.pack(side=RIGHT)\n",
    "    lmain2.place(x=900,y=350)\n",
    "    root.title(\"EMOJIS\")\n",
    "    root.geometry('1200x600+100+10')\n",
    "    root['bg']='black'\n",
    "    exitButton=Button(root,text='Quit',fg='red',command=root.destroy,font=('arial',25,'bold')).pack(side=BOTTOM)\n",
    "    threading.Thread(target=show_subject).start()\n",
    "    threading.Thread(target=show_avatar).start()\n",
    "    root.mainloop()\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3.8.8 ('base')",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.8"
  },
  "orig_nbformat": 4,
  "vscode": {
   "interpreter": {
    "hash": "b302cdd1e032ee910f5c889c3360c28564c92ad4f326fc3102e39fbe47faee66"
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
